name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alphax123/hello-node:latest
    - name: Push the Docker image
      run: docker login -u alphax123 -p ${{ secrets.docker_token }} && docker push alphax123/hello-node:latest